sonar.sources=frontend,lambdas
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=frontend/**
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/__pycache__/**,**/.terraform/**,**/*.zip
